import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Lang = 'ko' | 'en' | 'ja' | 'zh';
export type Theme = 'light' | 'dark';

const TRANSLATIONS = {
  ko: {
    appName: '로컬리',
    nav: {
      home: '홈',
      live: '실시간',
      tips: '꿀팁',
      travel: '여행',
      mypage: '마이',
      search: '검색',
      saved: '저장',
      emergency: '긴급',
      companions: '동행',
    },
    home: {
      citySelector: '서울·대한민국',
      cityTipCount: '현지 꿀팁',
      eventBanner: '🌸 벚꽃 개화 D-3',
      eventBannerSub: '피크닉 에티켓 보기 →',
      iAmAt: "I'm at a...",
      seeMore: '더 보기 →',
      todayPick: '오늘의 Pick',
      latestTips: '최신 꿀팁',
      seeAll: '전체 보기',
      searchPlaceholder: '꿀팁 검색...',
      recommend: '추천',
      latest: '최신',
      popular: '인기',
    },
    categories: {
      All: '전체',
      Transport: '교통',
      Food: '음식',
      Culture: '문화예절',
      Shopping: '쇼핑',
      Nightlife: '나이트라이프',
      Emergency: '긴급상황',
    },
    tips: {
      title: '로컬 팁',
      localExpert: '로컬 전문가',
      by: '작성자',
      empty: '이 카테고리에 팁이 없습니다.',
      saved: '저장됨',
      readMore: '더 보기',
      readLess: '접기',
      translation: '번역',
    },
    situations: {
      title: '지금 상황에 맞는\n꿀팁을 찾아요',
      subtitle: 'Find tips for your situation',
      restaurant: '식당',
      subway: '지하철',
      convenience: '편의점',
      pharmacy: '약국',
      taxi: '택시',
      norebang: '노래방',
      atm: 'ATM',
      accommodation: '숙소',
    },
    emergency: {
      title: '긴급 정보',
      subtitle: 'Emergency info · 緊急情報 · 紧急信息',
      offline: 'Offline',
      numbersTitle: '긴급 전화번호',
      phrasesTitle: '도움 요청 표현',
      police: '경찰',
      fire: '소방/응급',
      foreignMedical: '외국인 의료 상담',
      seoulHelpline: '다산콜 (서울)',
      helpMe: '도와주세요',
      doYouSpeakEnglish: '영어 하세요?',
      whereIsHospital: '병원 어디에요?',
      callAmbulance: '구급차 불러주세요',
      iAmLost: '길을 잃었어요',
      tapToSpeak: '눌러서 발음 듣기',
    },
    saved: {
      title: '저장한 꿀팁',
      empty: '마음에 드는 꿀팁을 저장해보세요.',
      emptyDesc: '여행 중 오프라인에서도 볼 수 있어요.',
      browseCta: '꿀팁 탐색하기 →',
    },
    submit: {
      title: '꿀팁 올리기',
      subtitle: '나의 경험 나누기',
      description: '누군가의 여행을 바꿉니다.',
      cancel: '취소',
      categoryLabel: '카테고리',
      contentLabel: '꿀팁 내용 (한국어)',
      contentPlaceholder: '현지인만 아는 꿀팁을 공유해주세요... (최소 20자)',
      aiLabel: 'AI 문화 번역 미리보기',
      aiButton: 'AI 번역 미리보기',
      aiHint: '아래 버튼을 눌러 AI번역을 생성하세요',
      aiGenerating: 'AI가 번역 중...',
      post: '게시하기',
      success: '등록되었습니다! 🎉',
      categories: {
        Transport: '교통 · Transportation',
        Food: '음식 · Food & Dining',
        Culture: '문화예절 · Etiquette',
        Emergency: '긴급상황 · Emergency',
        Other: '기타 · Other',
      },
    },
    companions: {
      title: '동행 매칭',
      subtitle: 'AI가 맞는 동행을 찾아드릴게요',
      myStyle: '내 여행 스타일',
      editStyle: '재진단 →',
      recommended: '추천 동행',
      all: '전체',
      requestBtn: '신청',
      profileBtn: '프로필 보기',
      matchRate: '스타일 일치',
      travelDate: '여행 일정',
    },
    myPage: {
      title: '아이페이지',
      profile: '내 프로필',
      guestUser: '여행자',
      guestEmail: '로그인이 필요합니다',
      tipsCount: '꿀팁',
      tripsCount: '여행',
      viewsCount: '조회',
      language: '언어',
      theme: '테마',
      themeLight: '라이트 모드',
      themeDark: '다크 모드',
      notifications: '알림 설정',
      notificationsDesc: '실시간 업데이트 알림 받기',
      about: '앱 정보',
      version: '버전',
      privacy: '개인정보 처리방침',
      terms: '서비스 이용약관',
      travelStyleQuiz: '여행 스타일 quiz',
      savedTips: '저장한 꿀팁',
      darkMode: '다크 모드',
      langNames: {
        ko: '한국어',
        en: 'English',
        ja: '日本語',
        zh: '中文',
      },
    },
    onboarding: {
      title: '여행 페르소나',
      subtitle: '당신에게 완벽한 로컬 플로우를 찾아드릴게요.',
      q1Title: '여행 페이스는?',
      q1Desc: '세밀한 계획파인가요, 즉흥 탐험가인가요?',
      q1A: '🐢 느긋하게 (여유파)',
      q1ASub: '동네 구석구석을 음미하며 여행하고 싶어요.',
      q1B: '⚡ 빠르게 (핫플 정복)',
      q1BSub: '모든 핫플레이스를 빠르게 정복하고 싶어요!',
      q2Title: '오늘 밤 우선순위는?',
      q2Desc: '서울의 해가 지면...',
      q2A: '🍖 K-BBQ & 소주',
      q2ASub: '최고의 현지 맛집으로 안내해주세요.',
      q2B: '🏮 야시장 & 야경',
      q2BSub: '도시의 야경과 길거리 음식을 즐기고 싶어요.',
      complete: '완료! 나만의 서울을 만나보세요.',
      resultTitle: '당신의 여행 스타일',
      goHome: '홈으로',
    },
  },
  en: {
    appName: '로컬리',
    nav: {
      home: 'Home',
      live: 'Live',
      tips: 'Tips',
      travel: 'Travel',
      mypage: 'My',
      search: 'Search',
      saved: 'Saved',
      emergency: 'SOS',
      companions: 'Mates',
    },
    home: {
      citySelector: 'Seoul · Korea',
      cityTipCount: 'local tips',
      eventBanner: '🌸 Cherry Blossom D-3',
      eventBannerSub: 'Picnic etiquette tips →',
      iAmAt: "I'm at a...",
      seeMore: 'See all →',
      todayPick: "Today's Pick",
      latestTips: 'Latest Tips',
      seeAll: 'See all',
      searchPlaceholder: 'Search tips...',
      recommend: 'Recommended',
      latest: 'Latest',
      popular: 'Popular',
    },
    categories: {
      All: 'All',
      Transport: 'Transport',
      Food: 'Food',
      Culture: 'Culture',
      Shopping: 'Shopping',
      Nightlife: 'Nightlife',
      Emergency: 'Emergency',
    },
    tips: {
      title: 'Local Tips',
      localExpert: 'Local Expert',
      by: 'By',
      empty: 'No tips in this category.',
      saved: 'Saved',
      readMore: 'Read more',
      readLess: 'Collapse',
      translation: 'Translation',
    },
    situations: {
      title: 'Find tips for\nyour situation',
      subtitle: 'Find tips for your situation',
      restaurant: 'Restaurant',
      subway: 'Subway',
      convenience: 'Convenience',
      pharmacy: 'Pharmacy',
      taxi: 'Taxi',
      norebang: 'Norebang',
      atm: 'ATM',
      accommodation: 'Stay',
    },
    emergency: {
      title: 'Emergency Info',
      subtitle: 'Emergency info · 緊急情報 · 紧急信息',
      offline: 'Offline',
      numbersTitle: 'Emergency Numbers',
      phrasesTitle: 'Help Phrases',
      police: 'Police',
      fire: 'Fire & EMS',
      foreignMedical: 'Foreign Medical',
      seoulHelpline: 'Seoul Helpline',
      helpMe: '도와주세요 (Help me)',
      doYouSpeakEnglish: '영어 하세요? (English?)',
      whereIsHospital: '병원 어디에요? (Hospital?)',
      callAmbulance: '구급차 불러주세요 (Ambulance)',
      iAmLost: '길을 잃었어요 (I\'m lost)',
      tapToSpeak: 'Tap to hear pronunciation',
    },
    saved: {
      title: 'Saved Tips',
      empty: 'Save tips you like.',
      emptyDesc: 'Access them offline while traveling.',
      browseCta: 'Browse tips →',
    },
    submit: {
      title: 'Share a Tip',
      subtitle: 'Share your experience',
      description: "Change someone's journey.",
      cancel: 'Cancel',
      categoryLabel: 'Category',
      contentLabel: 'Tip content (Korean)',
      contentPlaceholder: 'Share insider knowledge only locals know... (min 20 chars)',
      aiLabel: 'AI Translation Preview',
      aiButton: 'Preview AI Translation',
      aiHint: 'Press the button below to generate AI translation',
      aiGenerating: 'AI is translating...',
      post: 'Post',
      success: 'Posted! 🎉',
      categories: {
        Transport: '교통 · Transportation',
        Food: '음식 · Food & Dining',
        Culture: '문화예절 · Etiquette',
        Emergency: '긴급상황 · Emergency',
        Other: '기타 · Other',
      },
    },
    companions: {
      title: 'Travel Companion',
      subtitle: 'AI finds your perfect travel mate',
      myStyle: 'My Travel Style',
      editStyle: 'Retake quiz →',
      recommended: 'Recommended',
      all: 'All',
      requestBtn: 'Request',
      profileBtn: 'View Profile',
      matchRate: 'Style Match',
      travelDate: 'Travel Dates',
    },
    myPage: {
      title: 'My Page',
      profile: 'My Profile',
      guestUser: 'Traveler',
      guestEmail: 'Sign in to personalize',
      tipsCount: 'Tips',
      tripsCount: 'Trips',
      viewsCount: 'Views',
      language: 'Language',
      theme: 'Theme',
      themeLight: 'Light Mode',
      themeDark: 'Dark Mode',
      notifications: 'Notifications',
      notificationsDesc: 'Receive real-time updates',
      about: 'About',
      version: 'Version',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      travelStyleQuiz: 'Travel Style Quiz',
      savedTips: 'Saved Tips',
      darkMode: 'Dark Mode',
      langNames: {
        ko: '한국어',
        en: 'English',
        ja: '日本語',
        zh: '中文',
      },
    },
    onboarding: {
      title: 'Travel Persona',
      subtitle: "Let's find your perfect local flow.",
      q1Title: 'What is your local pace?',
      q1Desc: 'Are you a meticulous planner or a spontaneous wanderer?',
      q1A: '🐢 Slow & Steady',
      q1ASub: 'I want to soak in every detail of the neighborhood.',
      q1B: '⚡ Fast & Furious',
      q1BSub: 'I want to hit all the hot spots quickly!',
      q2Title: "What's your priority tonight?",
      q2Desc: 'When the sun goes down in Seoul...',
      q2A: '🍖 K-BBQ & Soju',
      q2ASub: 'Take me to the best local restaurants.',
      q2B: '🏮 Night Markets & Views',
      q2BSub: 'I want to see the city lights and street food.',
      complete: 'Done! Welcome to your Seoul.',
      resultTitle: 'Your Travel Style',
      goHome: 'Go Home',
    },
  },
  ja: {
    appName: '로컬리',
    nav: {
      home: 'ホーム',
      live: 'ライブ',
      tips: 'ヒント',
      travel: '旅行',
      mypage: 'マイ',
      search: '検索',
      saved: '保存',
      emergency: '緊急',
      companions: '同行',
    },
    home: {
      citySelector: 'ソウル・韓国',
      cityTipCount: 'ローカルヒント',
      eventBanner: '🌸 桜開花 D-3',
      eventBannerSub: 'ピクニックエチケットを見る →',
      iAmAt: "I'm at a...",
      seeMore: 'もっと見る →',
      todayPick: '今日のピック',
      latestTips: '最新ヒント',
      seeAll: '全て見る',
      searchPlaceholder: 'ヒントを検索...',
      recommend: 'おすすめ',
      latest: '最新',
      popular: '人気',
    },
    categories: {
      All: '全て',
      Transport: '交通',
      Food: '食べ物',
      Culture: 'カルチャー',
      Shopping: 'ショッピング',
      Nightlife: 'ナイトライフ',
      Emergency: '緊急',
    },
    tips: {
      title: 'ローカルヒント',
      localExpert: 'ローカル専門家',
      by: '投稿者',
      empty: 'このカテゴリーにヒントはありません。',
      saved: '保存済み',
      readMore: 'もっと読む',
      readLess: '折りたたむ',
      translation: '翻訳',
    },
    situations: {
      title: '今の状況に合う\nヒントを探そう',
      subtitle: 'Find tips for your situation',
      restaurant: 'レストラン',
      subway: '地下鉄',
      convenience: 'コンビニ',
      pharmacy: '薬局',
      taxi: 'タクシー',
      norebang: 'カラオケ',
      atm: 'ATM',
      accommodation: '宿泊',
    },
    emergency: {
      title: '緊急情報',
      subtitle: 'Emergency info · 緊急情報 · 紧急信息',
      offline: 'Offline',
      numbersTitle: '緊急電話番号',
      phrasesTitle: '助けを求める表現',
      police: '警察',
      fire: '消防/救急',
      foreignMedical: '外国人医療相談',
      seoulHelpline: 'ソウルヘルプライン',
      helpMe: '도와주세요 (助けて)',
      doYouSpeakEnglish: '영어 하세요? (英語話せますか?)',
      whereIsHospital: '병원 어디에요? (病院はどこ?)',
      callAmbulance: '구급차 불러주세요 (救急車を呼んで)',
      iAmLost: '길을 잃었어요 (道に迷いました)',
      tapToSpeak: 'タップして発音を聞く',
    },
    saved: {
      title: '保存したヒント',
      empty: '気に入ったヒントを保存しましょう。',
      emptyDesc: '旅行中オフラインでも見ることができます。',
      browseCta: 'ヒントを探す →',
    },
    submit: {
      title: 'ヒントを投稿',
      subtitle: '経験をシェアする',
      description: '誰かの旅を変えましょう。',
      cancel: 'キャンセル',
      categoryLabel: 'カテゴリー',
      contentLabel: 'ヒント内容（韓国語）',
      contentPlaceholder: 'ローカルだけが知るヒントをシェアしてください...',
      aiLabel: 'AI翻訳プレビュー',
      aiButton: 'AI翻訳プレビュー',
      aiHint: 'ボタンを押してAI翻訳を生成してください',
      aiGenerating: 'AIが翻訳中...',
      post: '投稿する',
      success: '投稿されました！ 🎉',
      categories: {
        Transport: '交通 · Transportation',
        Food: '음식 · Food & Dining',
        Culture: '文化 · Etiquette',
        Emergency: '緊急 · Emergency',
        Other: 'その他 · Other',
      },
    },
    companions: {
      title: '同行マッチング',
      subtitle: 'AIが最適な旅の同行者を見つけます',
      myStyle: '私の旅行スタイル',
      editStyle: '再診断 →',
      recommended: 'おすすめ',
      all: '全て',
      requestBtn: '申請',
      profileBtn: 'プロフィールを見る',
      matchRate: 'スタイル一致',
      travelDate: '旅行日程',
    },
    myPage: {
      title: '設定',
      profile: 'プロフィール',
      guestUser: '旅行者',
      guestEmail: 'サインインして個人化',
      tipsCount: 'ヒント',
      tripsCount: '旅行',
      viewsCount: '閲覧',
      language: '言語',
      theme: 'テーマ',
      themeLight: 'ライトモード',
      themeDark: 'ダークモード',
      notifications: '通知',
      notificationsDesc: 'リアルタイム更新通知を受け取る',
      about: 'アプリ情報',
      version: 'バージョン',
      privacy: 'プライバシーポリシー',
      terms: '利用規約',
      travelStyleQuiz: '旅行スタイルクイズ',
      savedTips: '保存したヒント',
      darkMode: 'ダークモード',
      langNames: {
        ko: '한국어',
        en: 'English',
        ja: '日本語',
        zh: '中文',
      },
    },
    onboarding: {
      title: '旅行ペルソナ',
      subtitle: 'あなただけのローカルフローを見つけましょう。',
      q1Title: 'あなたの旅行ペースは？',
      q1Desc: '計画派？それとも即興派？',
      q1A: '🐢 ゆっくり（じっくり派）',
      q1ASub: '街の細かいところまでじっくり味わいたいです。',
      q1B: '⚡ 速く（ホットスポット制覇）',
      q1BSub: '全てのホットスポットを素早く回りたいです！',
      q2Title: '今夜の優先事項は？',
      q2Desc: 'ソウルに日が暮れたら...',
      q2A: '🍖 K-BBQ & ソジュ',
      q2ASub: '最高のローカルレストランに連れて行って。',
      q2B: '🏮 夜市 & 夜景',
      q2BSub: '都市の夜景とストリートフードを楽しみたいです。',
      complete: '完了！あなただけのソウルへようこそ。',
      resultTitle: 'あなたの旅行スタイル',
      goHome: 'ホームへ',
    },
  },
  zh: {
    appName: '로컬리',
    nav: {
      home: '首页',
      live: '实时',
      tips: '攻略',
      travel: '旅行',
      mypage: '我的',
      search: '搜索',
      saved: '收藏',
      emergency: '紧急',
      companions: '同伴',
    },
    home: {
      citySelector: '首尔·韩国',
      cityTipCount: '本地攻略',
      eventBanner: '🌸 樱花开放 D-3',
      eventBannerSub: '野餐礼仪攻略 →',
      iAmAt: "I'm at a...",
      seeMore: '查看更多 →',
      todayPick: '今日精选',
      latestTips: '最新攻略',
      seeAll: '查看全部',
      searchPlaceholder: '搜索攻略...',
      recommend: '推荐',
      latest: '最新',
      popular: '热门',
    },
    categories: {
      All: '全部',
      Transport: '交通',
      Food: '美食',
      Culture: '文化',
      Shopping: '购物',
      Nightlife: '夜生活',
      Emergency: '紧急',
    },
    tips: {
      title: '本地攻略',
      localExpert: '本地专家',
      by: '作者',
      empty: '该类别暂无攻略。',
      saved: '已收藏',
      readMore: '阅读更多',
      readLess: '收起',
      translation: '翻译',
    },
    situations: {
      title: '找到适合\n当前情境的攻略',
      subtitle: 'Find tips for your situation',
      restaurant: '餐厅',
      subway: '地铁',
      convenience: '便利店',
      pharmacy: '药店',
      taxi: '出租车',
      norebang: 'KTV',
      atm: 'ATM',
      accommodation: '住宿',
    },
    emergency: {
      title: '紧急信息',
      subtitle: 'Emergency info · 緊急情報 · 紧急信息',
      offline: 'Offline',
      numbersTitle: '紧急电话号码',
      phrasesTitle: '求助用语',
      police: '警察',
      fire: '消防/急救',
      foreignMedical: '外国人医疗咨询',
      seoulHelpline: '首尔热线',
      helpMe: '도와주세요 (帮帮我)',
      doYouSpeakEnglish: '영어 하세요? (会说英语吗?)',
      whereIsHospital: '병원 어디에요? (医院在哪?)',
      callAmbulance: '구급차 불러주세요 (叫救护车)',
      iAmLost: '길을 잃었어요 (我迷路了)',
      tapToSpeak: '点击收听发音',
    },
    saved: {
      title: '收藏的攻略',
      empty: '收藏您喜欢的攻略。',
      emptyDesc: '旅行途中也可离线查看。',
      browseCta: '浏览攻略 →',
    },
    submit: {
      title: '分享攻略',
      subtitle: '分享你的经验',
      description: '改变某人的旅途。',
      cancel: '取消',
      categoryLabel: '类别',
      contentLabel: '攻略内容（韩语）',
      contentPlaceholder: '分享只有本地人才知道的秘诀...',
      aiLabel: 'AI翻译预览',
      aiButton: '预览AI翻译',
      aiHint: '按下按钮生成AI翻译',
      aiGenerating: 'AI正在翻译...',
      post: '发布',
      success: '发布成功！ 🎉',
      categories: {
        Transport: '交通 · Transportation',
        Food: '음식 · Food & Dining',
        Culture: '文化 · Etiquette',
        Emergency: '紧急 · Emergency',
        Other: '其他 · Other',
      },
    },
    companions: {
      title: '同伴匹配',
      subtitle: 'AI帮您找到完美旅伴',
      myStyle: '我的旅行风格',
      editStyle: '重新诊断 →',
      recommended: '推荐',
      all: '全部',
      requestBtn: '申请',
      profileBtn: '查看资料',
      matchRate: '风格匹配',
      travelDate: '旅行日期',
    },
    myPage: {
      title: '设置',
      profile: '个人资料',
      guestUser: '旅行者',
      guestEmail: '登录以个性化',
      tipsCount: '攻略',
      tripsCount: '旅行',
      viewsCount: '浏览',
      language: '语言',
      theme: '主题',
      themeLight: '浅色模式',
      themeDark: '深色模式',
      notifications: '通知',
      notificationsDesc: '接收实时更新通知',
      about: '关于应用',
      version: '版本',
      privacy: '隐私政策',
      terms: '服务条款',
      travelStyleQuiz: '旅行风格测试',
      savedTips: '收藏的攻略',
      darkMode: '深色模式',
      langNames: {
        ko: '한국어',
        en: 'English',
        ja: '日本語',
        zh: '中文',
      },
    },
    onboarding: {
      title: '旅行人格',
      subtitle: '让我们找到您完美的本地节奏。',
      q1Title: '您的旅行节奏是？',
      q1Desc: '您是计划派还是即兴探险者？',
      q1A: '🐢 慢慢来（悠闲派）',
      q1ASub: '我想细细品味每个角落。',
      q1B: '⚡ 快快走（打卡派）',
      q1BSub: '我想快速打卡所有热门景点！',
      q2Title: '今晚的优先事项是？',
      q2Desc: '首尔日落之后...',
      q2A: '🍖 韩式烤肉 & 烧酒',
      q2ASub: '带我去最好的本地餐厅。',
      q2B: '🏮 夜市 & 夜景',
      q2BSub: '我想看城市夜景和街边小吃。',
      complete: '完成！欢迎来到您的首尔。',
      resultTitle: '您的旅行风格',
      goHome: '返回首页',
    },
  },
} as const;

export type Translations = typeof TRANSLATIONS['ko'];

interface AppContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: Translations;
  homeSettingsOpen: boolean;
  openHomeSettings: () => void;
  closeHomeSettings: () => void;
}

const AppContext = createContext<AppContextType | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try { return (localStorage.getItem('lf_lang') as Lang) || 'ko'; } catch { return 'ko'; }
  });
  const [theme, setTheme] = useState<Theme>(() => {
    try { return (localStorage.getItem('lf_theme') as Theme) || 'dark'; } catch { return 'dark'; }
  });
  const [homeSettingsOpen, setHomeSettingsOpen] = useState(false);

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem('lf_lang', l); } catch {}
  };

  const toggleTheme = () => {
    setTheme(prev => {
      const next = prev === 'dark' ? 'light' : 'dark';
      try { localStorage.setItem('lf_theme', next); } catch {}
      return next;
    });
  };

  useEffect(() => {
    if (theme === 'dark') document.documentElement.classList.add('dark');
    else document.documentElement.classList.remove('dark');
  }, [theme]);

  const t = TRANSLATIONS[lang] as Translations;

  return (
    <AppContext.Provider value={{
      lang, setLang, theme, toggleTheme, t,
      homeSettingsOpen,
      openHomeSettings: () => setHomeSettingsOpen(true),
      closeHomeSettings: () => setHomeSettingsOpen(false),
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
